@extends('layouts.platform')

@section('title', 'Verification Services')

@section('content')
<div class="ivp-grid-2">
    <x-ui.card title="Request Verification" subtitle="Provider-neutral request entry.">
        <form class="vstack gap-3">
            <x-ui.select label="Service" name="service_code" :options="collect($services)->pluck('name', 'service_code')->all() ?: ['none' => 'No services configured']" />
            <x-ui.input label="Subject identifier" name="subject_identifier" placeholder="Customer identifier" />
            <x-ui.input label="Reference" name="reference" placeholder="Auto-generated by backend workflow" />
            <x-ui.alert variant="info" icon="fa-circle-info">Submitting requests will be wired to the existing Verification Service workflow in the next UX sprint.</x-ui.alert>
            <x-ui.button type="button" variant="primary" icon="fa-id-card">Prepare Request</x-ui.button>
        </form>
    </x-ui.card>

    <x-ui.card title="Service Pricing" subtitle="Current verification catalog pricing.">
        <x-ui.table
            :headers="['Service', 'Code', 'Price', 'Status']"
            :rows="collect($services)->map(fn ($row) => [
                e($row['name'] ?? '-'),
                e($row['service_code'] ?? '-'),
                e(($row['currency'] ?? 'NGN').' '.number_format((float) ($row['default_price'] ?? 0), 2)),
                view('components.ui.status-badge', ['status' => $row['status'] ?? 'active'])->render(),
            ])->all()"
            empty="No verification services configured."
        />
    </x-ui.card>
</div>

<x-ui.card class="mt-3" title="Request History" subtitle="Status tracking and result access.">
    <x-ui.table
        :headers="['Reference', 'Provider', 'Amount', 'Status', 'Created']"
        :rows="collect($requests)->map(fn ($row) => [
            e($row['reference'] ?? '-'),
            e($row['provider'] ?? '-'),
            e(($row['currency'] ?? 'NGN').' '.number_format((float) ($row['price_charged'] ?? 0), 2)),
            view('components.ui.status-badge', ['status' => $row['status'] ?? 'created'])->render(),
            e((string) ($row['created_at'] ?? '-')),
        ])->all()"
        empty="No verification requests yet."
    />
</x-ui.card>
@endsection
